import { Project, BlogPost, ServiceItem, StudioInfo, ProcessStep, FaqItem, InteriorPackage, GalleryPhoto } from './types';

export const STUDIO_INFO: StudioInfo = {
  name: 'Kalyan Design Studio',
  legalName: 'Kalyan Design Studio',
  tagline: 'Best Interior Design Company in Bhubaneswar, Odisha',
  metaDescription: "Kalyan Design Studio, Bhubaneswar's top interior designer, transforms spaces with elegant, functional designs. Residential & commercial projects. Call now!",
  keywords: [
    'Interior Design Bhubaneswar',
    'Best Interior Designers in Odisha',
    'Luxury Interior Design Odisha',
    'Home Decor Services Bhubaneswar',
    'Modular Kitchen Bhubaneswar',
    'False Ceiling Odisha',
  ],
  contact: {
    phone: '+91-0750404104',
    phoneDisplay: '+91 75040 41040',
    email: 'info@kalyandesignstudio.com',
    address: {
      street: '3181/5466, Puri-NH Bypass, Baragada',
      locality: 'Bhubaneswar',
      region: 'Odisha',
      postalCode: '751018',
      country: 'India',
      formattedAddress: '3181/5466, Puri-NH Bypass, Baragada, Bhubaneswar, Odisha 751018',
    },
    geo: {
      latitude: 20.296059,
      longitude: 85.824539,
    },
    openingHours: {
      days: 'Monday – Saturday',
      hours: '10:00 AM – 8:00 PM',
      sunday: 'Closed / By Appointment',
    },
    googleMapsEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d14703.497116044074!2d85.86106134999999!3d20.251747199999998!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3a19a76aa3db6109%3A0x9796e53a6bd98373!2sKalyan+Design+Studio!5e0!3m2!1sen!2sin!4v1633363360744!5m2!1sen!2sin',
    googleBusinessProfileUrl: 'https://g.co/kgs/VwVxACj',
    socialLinks: {
      facebook: 'https://www.facebook.com/kalyandesignstudio?mibextid=qi2Omg&rdid=MHLyk3ZtVcuF1RKv&share_url=https%3A%2F%2Fwww.facebook.com%2Fshare%2FrkDRD6iso3sg4iDR%2F%3Fmibextid%3Dqi2Omg',
      instagram: 'https://www.instagram.com/kalyan_design_studio?igsh=N2U3ZmJ1N210Mmhs',
      youtube: 'https://www.youtube.com/watch?si=yv5otNwI-2c43qK8&v=ACrraXQOfuQ&feature=youtu.be',
    },
  },
  branding: {
    logo: '/images/kalyan/branding/logo.png',
    logoWebp: '/images/kalyan/blog/LOGO.webp',
    footerBg: '/images/kalyan/branding/footer.png',
    contactBg: '/images/kalyan/assets/contactbackg-D9XEOEFC.png',
  },
};

export const HERO_LETTER_IMAGES = {
  K: [
    {
      url: '/images/kalyan/assets/oo4-DLB_pEqh.png',
      title: 'Bespoke Architectural Living Room — Kalyan Studio',
    },
    {
      url: '/images/kalyan/assets/oo2-rS0nPjmx.png',
      title: 'Master Bedroom Aesthetic Suite — Kalyan Design Studio',
    },
    {
      url: '/images/kalyan/assets/gg1-DtHpufY2.png',
      title: 'Signature Modular Kitchen Showcase',
    },
    {
      url: '/images/kalyan/assets/kk1-CiuMHIoo.png',
      title: 'Artisan Wood Paneling & Ambient Illuminations',
    },
  ],
  Y: [
    {
      url: '/images/kalyan/assets/oo5-D62wu78I.png',
      title: 'Double Height Luxury Villa Living Space',
    },
    {
      url: '/images/kalyan/assets/oo3-CiU3wIec.png',
      title: 'Architectural Dining & Open Concept Lounge',
    },
    {
      url: '/images/kalyan/assets/gg2-CMv5Ld9X.png',
      title: 'Bespoke Architectural Fluted Partitions',
    },
    {
      url: '/images/kalyan/assets/kk2-1EypKmCq.png',
      title: 'Contemporary Accent Ceilings & Lighting',
    },
  ],
  N: [
    {
      url: '/images/kalyan/assets/oo2-rS0nPjmx.png',
      title: 'Signature Kalyan Master Living Suite',
    },
    {
      url: '/images/kalyan/assets/oo4-DLB_pEqh.png',
      title: 'Grand Residential Entry & Foyer Design',
    },
    {
      url: '/images/kalyan/assets/oo5-D62wu78I.png',
      title: 'Executive Corporate Penthouse & Lounge',
    },
    {
      url: '/images/kalyan/assets/oo3-CiU3wIec.png',
      title: 'Bhubaneswar Premium Residence by Kalyan',
    },
  ],
};

export const PROJECTS: Project[] = [
  {
    id: 'kyn-proj-01',
    slug: 'bhubaneswar-interior-design-project',
    title: 'Bhubaneswar Interior Design Project',
    category: 'residential',
    location: 'Bhubaneswar, Odisha',
    year: 2025,
    areaSqFt: 6200,
    image: '/images/kalyan/assets/my1-CiB3FE8i.png',
    gallery: [
      '/images/kalyan/gallery/photo1.png',
      '/images/kalyan/gallery/photo2.png',
      '/images/kalyan/gallery/photo3.png',
    ],
    description: 'Discover the artistry of interior design in Bhubaneswar. Our project showcases modern aesthetics blended with functionality to create breathtaking spaces with acoustic ceiling treatments and custom joinery.',
    client: 'Private Residence Owner',
    featured: true,
    materials: ['Boiling Water Resistant Marine Ply', 'Italian Statuario Marble', 'Architectural Gypsum', 'Warm Teak Veneer'],
  },
  {
    id: 'kyn-proj-02',
    slug: 'ranga-bazar-bhubaneswar-interior-design',
    title: 'Ranga Bazar Interior Design',
    category: 'residential',
    location: 'Ranga Bazar, Bhubaneswar',
    year: 2025,
    areaSqFt: 5400,
    image: '/images/kalyan/assets/my2-ZuwLd7VG.png',
    gallery: [
      '/images/kalyan/gallery/photo4.png',
      '/images/kalyan/gallery/photo5.png',
      '/images/kalyan/gallery/photo6.png',
    ],
    description: 'Experience the transformation of indoor spaces in Ranga Bazar, Bhubaneswar. This project redefines elegance and functionality with seamless modular cabinetry and ambient perimeter cove lighting.',
    client: 'Heritage Business Family',
    featured: true,
    materials: ['Quartz Countertops', 'Fluted Charcoal Panels', 'Brushed Brass Joinery', 'Low-VOC Matte Emulsion'],
  },
  {
    id: 'kyn-proj-03',
    slug: '3d-parlour-design-project',
    title: '3D Commercial Parlour & Salon Design',
    category: 'commercial',
    location: 'Bhubaneswar, Odisha',
    year: 2024,
    areaSqFt: 3800,
    image: '/images/kalyan/assets/my3-DfYMVO0a.png',
    gallery: [
      '/images/kalyan/gallery/photo7.png',
      '/images/kalyan/gallery/photo8.png',
      '/images/kalyan/gallery/photo9.png',
    ],
    description: 'Explore our 3D Parlour Design project that combines innovation with style for an unforgettable luxury experience. Raytraced 3D modeling enabled complete client visualization before on-site fit-out.',
    client: 'Luxury Salon & Wellness Studio',
    featured: true,
    materials: ['High-Traffic Terrazzo', 'Mirror Integrated Ambient Rings', 'Acoustic Wall Panels', 'Ergonomic Styling Units'],
  },
  {
    id: 'kyn-proj-04',
    slug: 'nandan-vihar-bhubaneswar-interior-renovation',
    title: 'Nandan Vihar Duplex Renovation',
    category: 'penthouse',
    location: 'Nandan Vihar, Bhubaneswar',
    year: 2025,
    areaSqFt: 5800,
    image: '/images/kalyan/assets/my4-DDISAuaV.png',
    gallery: [
      '/images/kalyan/gallery/photo10.png',
      '/images/kalyan/gallery/photo11.png',
      '/images/kalyan/gallery/photo12.png',
    ],
    description: 'Redefining interiors at Nandan Vihar, Bhubaneswar. This project emphasizes comfort and sophistication with open-concept living, custom TV consoles, and double-height architectural glass.',
    client: 'Senior Tech Executive',
    featured: true,
    materials: ['Bespoke Media Console', 'Concealed LED Strip Lighting', 'Natural Burma Teak', 'Vitrified Large Slab Tiles'],
  },
  {
    id: 'kyn-proj-05',
    slug: 'sundarpada-basra-home-interior',
    title: 'Sundarpada Basra Modern Residence',
    category: 'residential',
    location: 'Sundarpada, Basra, Bhubaneswar',
    year: 2024,
    areaSqFt: 4600,
    image: '/images/kalyan/assets/my5-BeOxY4Xv.png',
    gallery: [
      '/images/kalyan/gallery/photo13.png',
      '/images/kalyan/gallery/photo14.png',
      '/images/kalyan/gallery/photo15.png',
    ],
    description: 'Sundarpada, Basra’s home interior project highlights minimalist design principles with a touch of modern charm. Floor-to-ceiling wardrobes and a master bedroom acoustic suite.',
    client: 'Civil Infrastructure Leader',
    featured: true,
    materials: ['Floor-to-Ceiling Wardrobes', 'Soft-Close Hardware', 'Gypsum Plasterboards', 'Anti-Fungal Plywood'],
  },
  {
    id: 'kyn-proj-06',
    slug: 'koraput-office-design',
    title: 'Koraput Executive Corporate Office',
    category: 'commercial',
    location: 'Koraput, Odisha',
    year: 2024,
    areaSqFt: 8200,
    image: '/images/kalyan/assets/my6-BO-EvvWK.png',
    gallery: [
      '/images/kalyan/gallery/photo16.png',
      '/images/kalyan/gallery/photo17.png',
      '/images/kalyan/gallery/photo18.png',
    ],
    description: 'Koraput office design project blends professional aesthetics with optimal functionality for a high-performance workspace, executive conference suites, and corporate reception lounge.',
    client: 'Regional Enterprise Headquarters',
    featured: true,
    materials: ['Acoustic Ceiling Tiles', 'Toughened Glass Partitions', 'Ergonomic Modular Desks', 'Commercial Carpet Flooring'],
  },
  {
    id: 'kyn-proj-07',
    slug: 'cuttack-residential-interior',
    title: 'Cuttack Riverfront Residential Interior',
    category: 'residential',
    location: 'Cuttack, Odisha',
    year: 2025,
    areaSqFt: 6900,
    image: '/images/kalyan/assets/my7-C6hJC8la.png',
    gallery: [
      '/images/kalyan/gallery/photo19.png',
      '/images/kalyan/gallery/photo20.png',
      '/images/kalyan/gallery/photo21.png',
    ],
    description: 'Transforming homes in Cuttack with modern residential interior design ideas that cater to every need, incorporating climate-responsive ventilation and river breeze orientation.',
    client: 'Prominent Judicial Family',
    featured: false,
    materials: ['Honed Natural Granite', 'Teak Wood Panelling', 'Designer Gypsum Ceilings', 'Weather-Resistant Finishes'],
  },
  {
    id: 'kyn-proj-08',
    slug: 'cuttack-second-site-design',
    title: 'Cuttack Heritage Bungalow Revitalization',
    category: 'residential',
    location: 'Cuttack, Odisha',
    year: 2024,
    areaSqFt: 5100,
    image: '/images/kalyan/assets/my8-Cg_lAXr_.png',
    gallery: [
      '/images/kalyan/gallery/photo22.png',
      '/images/kalyan/gallery/photo23.png',
      '/images/kalyan/gallery/photo24.png',
    ],
    description: 'Explore our second interior design project in Cuttack, crafted with precision and artistic vision, celebrating regional architecture with contemporary comfort.',
    client: 'Healthcare Entrepreneur',
    featured: false,
    materials: ['Heritage Terracotta Elements', 'Modern Brass Inlays', 'Bespoke Wardrobe Suites', 'Warm Ambient Sconces'],
  },
];

export const SERVICES: ServiceItem[] = [
  {
    id: 'srv-01',
    slug: 'modular_kitchen',
    title: 'Modular Kitchen',
    subtitle: 'Heart of the Home & Culinary Luxury',
    description: 'The kitchen is the heartbeat of every home and celebration. Our custom modular kitchens optimize layout, boiling-water-resistant cabinetry, quartz countertops, and built-in appliances for supreme durability and joy.',
    features: ['Customized layout for any space', 'Boiling Water Resistant (BWR) marine plywood', 'Soft-close tandem drawers & corner carousels', 'Built-in appliance integration & chimney ducting'],
    icon: 'Compass',
    metric: '10-Year Carcass Durability',
    image: '/images/kalyan/assets/MODULARKITCHEN-DIgipoZG.png',
  },
  {
    id: 'srv-02',
    slug: '3d_interiormodels',
    title: '3D Interior Models',
    subtitle: 'Photorealistic Simulation & Virtual Walkthroughs',
    description: '3D models are a potent tool to visualize your space in photorealistic detail before execution. Experience daytime and dusk lighting, experiment with materials, and approve layouts with 100% confidence.',
    features: ['Photorealistic raytraced 3D walkthroughs', 'Interactive textures and material preview', 'Accurate daylight and ambient lighting models', 'Zero guesswork before civil execution'],
    icon: 'Palette',
    metric: '100% Visual Accuracy',
    image: '/images/kalyan/assets/3DINTERIORMODELS-Bz_sO8Pe.png',
  },
  {
    id: 'srv-03',
    slug: 'tv_cabinet',
    title: 'TV Cabinet & Feature Walls',
    subtitle: 'Bespoke Entertainment Consoles',
    description: 'Bespoke media consoles engineered with invisible cable management, acoustic fluted louvers, back-lit marble niches, and tailored storage compartments for modern living rooms.',
    features: ['Low & high profile custom configurations', 'Concealed channels for 100% hidden wiring', 'Acoustic fluted panelling & warm cove lighting', 'Integrated display shelving & gaming drawers'],
    icon: 'Building2',
    metric: 'Invisible Cable Design',
    image: '/images/kalyan/assets/TVCABINEI-CzWsC3Up.png',
  },
  {
    id: 'srv-04',
    slug: 'gypsum_celling',
    title: 'Gypsum False Ceiling',
    subtitle: 'Acoustic Absorption & Thermal Insulation',
    description: 'Drywall false ceilings made from hydrated calcium sulfate boards that absorb noise, improve room acoustics, and reduce air-conditioning energy costs during Odisha’s hot summers.',
    features: ['Superior sound dampening & theater acoustics', 'Thermal barrier reducing cooling electricity costs', 'Seamless cove profiles for indirect ambient lighting', 'Fire-resistant & crack-proof smooth finish'],
    icon: 'Sparkles',
    metric: 'Energy & Acoustic Efficient',
    image: '/images/kalyan/assets/GYPSUMCELLING-N_O6msDY.png',
  },
  {
    id: 'srv-05',
    slug: 'pvc_ceiling',
    title: 'PVC Ceiling Panels',
    subtitle: '100% Waterproof & Termite Proof',
    description: 'Lightweight engineered polymer ceiling panels offering zero maintenance, complete moisture resistance, and wood-grain elegance for balconies, kitchens, and contemporary living spaces.',
    features: ['Immune to coastal dampness and termites', 'Zero painting required — wipe clean maintenance', 'Authentic wood-grain and stone textures', 'Designed for recessed LED spotlight profiles'],
    icon: 'Compass',
    metric: 'Zero-Maintenance Solution',
    image: '/images/kalyan/assets/7th-BwavL1Pi.png',
  },
  {
    id: 'srv-06',
    slug: 'core_house_plan',
    title: 'Core House Plan',
    subtitle: 'Comprehensive 2D/3D Floor Architecture',
    description: 'Master structural and spatial blueprints outlining room dimensions, Vastu zoning, circulation flow, exterior front elevations, and complete MEP coordination.',
    features: ['Vastu-harmonized spatial orientation', 'Precise 2D floor plans & millimeter dimensions', 'Exterior front, rear, and lateral elevations', 'Complete site & structural layout coordination'],
    icon: 'Building2',
    metric: 'Full Blueprint Package',
    image: '/images/kalyan/assets/project5-CUTtopKF.png',
  },
  {
    id: 'srv-07',
    slug: 'wardrobe',
    title: 'Custom Wardrobes',
    subtitle: 'Floor-to-Ceiling Closets & Dressing Suites',
    description: 'Custom modern wardrobes with floor-to-ceiling sliding systems, double hanging rods, internal vanity mirrors, and sensor-activated illumination tailored to your exact wardrobe needs.',
    features: ['Floor-to-ceiling sliding and hinged configurations', 'Double-hanging rods & saree/coat organizers', 'Sensor-activated internal LED lighting', 'Anti-fungal, moisture-sealed edge-banded carcass'],
    icon: 'Palette',
    metric: 'Tailored Storage Capacity',
    image: '/images/kalyan/assets/Wardrobe-DUVZi608.png',
  },
];

export const PROCESS_STEPS: ProcessStep[] = [
  {
    step: 1,
    title: 'BRIEFING',
    icon: 'ri-lightbulb-flash-line',
    description: 'We begin with an exhaustive questionnaire to fully grasp the vision, needs and expectations of the Client. Getting the brief right is key to success of the project.',
  },
  {
    step: 2,
    title: 'DESIGN',
    icon: 'ri-edit-line',
    description: 'Translating the brief into the design blueprint is the next step. We start with a 2-D floor plan followed by 3-D visualisation of the space. This helps paint a vivid picture of the eventual look and feel of the interiors for the client.',
  },
  {
    step: 3,
    title: 'EXECUTION',
    icon: 'ri-megaphone-fill',
    description: 'This is where the design comes to life. We undertake only end-end projects and aim for perfection in every inch. Along with our handpicked team of craftsmen and vendors from across the world, we deliver a globally-inspired functional work of art.',
  },
  {
    step: 4,
    title: 'HANDOVER',
    icon: 'ri-key-2-fill',
    description: 'This marks the culmination of an exciting journey for both the client and us as we handover the keys to their new home. A space all set to delight the occupants for years to come.',
  },
];

export const FAQS: FaqItem[] = [
  {
    id: 'faq-01',
    question: 'WHAT EXACTLY DOES AN INTERIOR DESIGNER DO?',
    answer: 'An interior designer specializes in creating functional, aesthetically appealing, and safe interior spaces by strategically selecting materials, colors, furniture, lighting, and finishes. They work closely with clients to understand their preferences and requirements, ensuring the design aligns with both style and functionality while adhering to building codes and regulations.',
  },
  {
    id: 'faq-02',
    question: 'WHAT IS THE ROLE OF THE INTERIOR DESIGNER?',
    answer: 'The role of an interior designer involves conceptualizing and executing design solutions that enhance the functionality and visual appeal of interior spaces. They collaborate with clients to understand their needs, select appropriate materials, and ensure compliance with safety standards, while balancing aesthetics, practicality, and environmental considerations.',
  },
  {
    id: 'faq-03',
    question: 'WHAT ARE THE 7 ELEMENTS OF INTERIOR DESIGN?',
    answer: 'The seven key elements of interior design are space, line, form, light, color, texture, and pattern. These elements work together to create harmonious and functional interiors. By balancing these components, interior designers craft visually appealing, comfortable, and practical spaces that align with the client’s needs and preferences.',
  },
  {
    id: 'faq-04',
    question: 'DOES INTERIOR DESIGN INCLUDES FURNITURE?',
    answer: 'Yes, interior design includes furniture as a critical component. Furniture enhances functionality, defines space, and contributes to the overall aesthetic of a design. Interior designers select and arrange furniture to complement the design concept, ensuring it aligns with spatial planning, ergonomics, and the client’s style preferences.',
  },
  {
    id: 'faq-05',
    question: 'WHY INTERIOR DESIGN?',
    answer: 'Interior design is essential for creating functional, aesthetically pleasing environments that enhance the quality of life. It optimizes space, improves safety, and fosters comfort, reflecting personal or brand identity. By harmonizing elements like color, texture, and lighting, interior design transforms spaces into cohesive, purposeful environments tailored to users\' needs.',
  },
];

export const GALLERY_PHOTOS: GalleryPhoto[] = [
  { id: 1, image: '/images/kalyan/gallery/photo1.png', title: 'Bhubaneswar Living Lounge', category: 'residential' },
  { id: 2, image: '/images/kalyan/gallery/photo2.png', title: 'Master Bedroom Acoustic Suite', category: 'residential' },
  { id: 3, image: '/images/kalyan/gallery/photo3.png', title: 'Contemporary Dining & Bar', category: 'residential' },
  { id: 4, image: '/images/kalyan/gallery/photo4.png', title: 'Modular Chef Kitchen', category: 'residential' },
  { id: 5, image: '/images/kalyan/gallery/photo5.png', title: 'Executive Workstation Corner', category: 'commercial' },
  { id: 6, image: '/images/kalyan/gallery/photo6.png', title: 'Fluted Wall & Media Console', category: 'residential' },
  { id: 7, image: '/images/kalyan/gallery/photo7.png', title: '3D Commercial Parlour Reception', category: 'commercial' },
  { id: 8, image: '/images/kalyan/gallery/photo8.png', title: 'Luxury Salon Styling Station', category: 'commercial' },
  { id: 9, image: '/images/kalyan/gallery/photo9.png', title: 'Illuminated Wash & Spa Area', category: 'commercial' },
  { id: 10, image: '/images/kalyan/gallery/photo10.png', title: 'Nandan Vihar Duplex Lounge', category: 'residential' },
  { id: 11, image: '/images/kalyan/gallery/photo11.png', title: 'Minimalist Teak Foyer', category: 'residential' },
  { id: 12, image: '/images/kalyan/gallery/photo12.png', title: 'Open Concept Living Area', category: 'residential' },
  { id: 13, image: '/images/kalyan/gallery/photo13.png', title: 'Sundarpada Private Residence', category: 'residential' },
  { id: 14, image: '/images/kalyan/gallery/photo14.png', title: 'Ambient Bedside Panelling', category: 'residential' },
  { id: 15, image: '/images/kalyan/gallery/photo15.png', title: 'Walk-in Wardrobe Dressing Room', category: 'residential' },
  { id: 16, image: '/images/kalyan/gallery/photo16.png', title: 'Koraput Executive Office', category: 'commercial' },
  { id: 17, image: '/images/kalyan/gallery/photo17.png', title: 'Corporate Conference Room', category: 'commercial' },
  { id: 18, image: '/images/kalyan/gallery/photo18.png', title: 'Reception & Waiting Lounge', category: 'commercial' },
  { id: 19, image: '/images/kalyan/gallery/photo19.png', title: 'Cuttack Riverfront Residence', category: 'residential' },
  { id: 20, image: '/images/kalyan/gallery/photo20.png', title: 'Architectural Gypsum False Ceiling', category: 'residential' },
  { id: 21, image: '/images/kalyan/gallery/photo21.png', title: 'Custom TV Cabinet & Storage', category: 'residential' },
  { id: 22, image: '/images/kalyan/gallery/photo22.png', title: 'Cuttack Heritage Bungalow', category: 'residential' },
  { id: 23, image: '/images/kalyan/gallery/photo23.png', title: 'Warm Wood Grain Dining Hall', category: 'residential' },
  { id: 24, image: '/images/kalyan/gallery/photo24.png', title: 'Children Study & Bedroom', category: 'residential' },
  { id: 25, image: '/images/kalyan/gallery/photo25.png', title: 'Compact Apartment Kitchenette', category: 'residential' },
  { id: 26, image: '/images/kalyan/gallery/photo26.png', title: 'Guest Suite Powder Room', category: 'residential' },
  { id: 27, image: '/images/kalyan/gallery/photo27.png', title: 'Terrace Lounge & Sitting Area', category: 'residential' },
  { id: 28, image: '/images/kalyan/gallery/photo28.png', title: 'Modern Puja Room Mandir Design', category: 'residential' },
];

export const INTERIOR_PACKAGES: InteriorPackage[] = [
  {
    id: 'pkg-01',
    name: 'Essential Turnkey Package',
    idealFor: '1BHK / 2BHK Starter Residences',
    image: '/images/kalyan/assets/img1-CC7S1ZnS.png',
    highlights: [
      'Modular Kitchen with BWR plywood & soft close hardware',
      'Gypsum false ceiling in living room with LED coves',
      'Master bedroom wardrobe with internal mirrors',
      'Full TV cabinet with cable management',
    ],
  },
  {
    id: 'pkg-02',
    name: 'Premium Residence Package',
    idealFor: '3BHK & Duplex Homes',
    image: '/images/kalyan/assets/img2-DGLXbayj.png',
    highlights: [
      'Luxury modular kitchen with quartz countertop & tandem boxes',
      'Complete house false ceiling with perimeter lighting',
      'Floor-to-ceiling wardrobes for 3 bedrooms',
      'Fluted acoustic TV unit and dining partition screen',
    ],
  },
  {
    id: 'pkg-03',
    name: 'Luxury Bespoke Villa Package',
    idealFor: 'Villas, Penthouses & Commercial Spaces',
    image: '/images/kalyan/assets/img3-CT8lRwuI.png',
    highlights: [
      'End-to-end custom architectural interior execution',
      'Italian marble, seasoned Burma teak, and brass accents',
      '3D photorealistic visualization & Vastu consultation',
      'Smart lighting automation & dedicated site supervisor',
    ],
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'wp-post-743',
    slug: 'the-psychology-of-colors-in-interior-design',
    title: 'The Psychology of Colors in Interior Design: Unlocking the Power of Hue',
    excerpt: 'Discover how the psychology of colors in interior design can transform your living spaces. Learn to create the perfect mood and atmosphere with strategic color choices.',
    date: 'February 2025',
    readTime: '6 min read',
    category: 'Color Theory & Well-being',
    image: '/images/kalyan/blog/Warm-Colors-in-Interior-Design-1.jpg',
    author: {
      name: 'Kalyan Design Studio Editorial',
      role: 'Principal Interior Architecture Team',
      avatar: '/images/kalyan/branding/logo.png',
    },
    content: "Did you know we can see about 10 million different colors? This amazing ability is key in color psychology in interior design. Colors do more than just look good – they change how we feel in a space. Color psychology is all about how colors affect our mood and behavior. When we pick colors for our homes, we're not just picking paint. We're creating a feeling in our living spaces.",
  },
  {
    id: 'post-02',
    slug: 'modern-interior-architecture-odisha',
    title: 'Modern Architecture in Odisha: Balancing Tropical Climate with Quiet Luxury',
    excerpt: 'How contemporary residences in Bhubaneswar and Cuttack are utilizing natural sandstone, courtyards, and deep overhangs to stay naturally cool and luxurious.',
    date: 'March 2026',
    readTime: '5 min read',
    category: 'Regional Architecture',
    image: '/images/kalyan/gallery/photo1.png',
    author: {
      name: 'Kalyan Design Studio',
      role: 'Design Director',
      avatar: '/images/kalyan/branding/logo.png',
    },
  },
  {
    id: 'post-03',
    slug: 'teak-and-laterite-craftsmanship',
    title: 'The Revival of Teak and Laterite in Contemporary Odia Homes',
    excerpt: 'Exploring how local materials can be reimagined with minimalist joinery techniques for timeless durability in coastal and riverfront climates.',
    date: 'February 2026',
    readTime: '7 min read',
    category: 'Material Innovation',
    image: '/images/kalyan/gallery/photo4.png',
    author: {
      name: 'Kalyan Design Studio',
      role: 'Material Specialist',
      avatar: '/images/kalyan/branding/logo.png',
    },
  },
];

export const AGENCY_STATS = [
  { value: '150+', label: 'Residential & Commercial Projects Completed' },
  { value: '10+', label: 'Years of Interior Architecture in Odisha' },
  { value: '100%', label: 'Turnkey Delivery Guarantee' },
  { value: '4.9 ★', label: 'Client Rating & Google Trust' },
];

export const CLIENT_TESTIMONIALS = [
  {
    quote: 'Kalyan Design Studio transformed our home in Bhubaneswar into a dream sanctuary. From 3D models to final execution, the craftsmanship in our modular kitchen and gypsum ceiling is flawless.',
    client: 'Ritika Sharma',
    location: 'Bhubaneswar, Odisha',
    role: 'Homeowner',
  },
  {
    quote: 'Their attention to detail on our Cuttack residence was exceptional. Transparent budgets, on-time handover, and stunning aesthetic finishes that our guests constantly admire.',
    client: 'Debabrata Mohapatra',
    location: 'Cuttack, Odisha',
    role: 'Managing Director',
  },
  {
    quote: 'The 3D interior walkthrough gave us complete confidence before any civil work started. Kalyan Studio handled everything turnkey from start to finish with great professionalism.',
    client: 'Er. Rajesh Mishra',
    location: 'Patia, Bhubaneswar',
    role: 'Villa Owner',
  },
];
